### ISSUE TITLE
Seems it didn't work on 1.21.11

### ISSUE THREAD

**Issue by xfy2412** [Deanveloper/SkullCreator#28]
[13:53:45 ERROR]: Could not pass event InventoryClickEvent to MGMC-Paper v1.0.0
java.lang.NoSuchMethodError: 'com.mojang.authlib.properties.PropertyMap com.mojang.authlib.GameProfile.getProperties()'
at mgmc-paper-1.0-SNAPSHOT.jar//day.dean.skullcreator.SkullCreator.makeProfile(SkullCreator.java:269) ~[?:?]
at mgmc-paper-1.0-SNAPSHOT.jar//day.dean.skullcreator.SkullCreator.mutateItemMeta(SkullCreator.java:300) ~[?:?]
at mgmc-paper-1.0-SNAPSHOT.jar//day.dean.skullcreator.SkullCreator.itemWithBase64(SkullCreator.java:163) ~[?:?]
at mgmc-paper-1.0-SNAPSHOT.jar//ltd.opens.mg.paper.MGMCPlugin.fillPlayerManagementMenu(MGMCPlugin.java:451) ~[?:?]
at mgmc-paper-1.0-SNAPSHOT.jar//ltd.opens.mg.paper.MGMCPlugin.openPlayerManagementMenu(MGMCPlugin.java:362) ~[?:?]
at mgmc-paper-1.0-SNAPSHOT.jar//ltd.opens.mg.paper.MGMCPlugin.handleMenuClick(MGMCPlugin.java:323) ~[?:?]
at mgmc-paper-1.0-SNAPSHOT.jar//ltd.opens.mg.paper.MGMCPlugin$1.onInventoryClick(MGMCPlugin.java:95) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.11-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:71) ~[paper-api-1.21.11-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.11-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3297) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:59) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:14) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at net.minecraft.network.PacketProcessor$ListenerAndPacket.handle(PacketProcessor.java:99) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at net.minecraft.network.PacketProcessor.executeSinglePacket(PacketProcessor.java:33) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at net.minecraft.server.MinecraftServer.runAllTasksAtTickStart(MinecraftServer.java:1180) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at net.minecraft.server.MinecraftServer.processPacketsAndTick(MinecraftServer.java:1666) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:388) ~[paper-1.21.11.jar:1.21.11-117-79c77f5]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
